on: [push, pull_request, workflow_dispatch]

name: CI

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - run: rustc -vV
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  #check:
  #  name: Check
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions-rs/toolchain@v1
  #      with:
  #        profile: minimal
  #        toolchain: stable
  #        override: true
  #    - run: rustc -vV
  #    - uses: actions-rs/cargo@v1
  #      with:
  #        command: check
  #        args: --workspace --all-targets --all-features

  #clippy:
  #  name: Clippy
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions-rs/toolchain@v1
  #      with:
  #        profile: minimal
  #        toolchain: stable
  #        override: true
  #        components: clippy
  #    - run: rustc -vV
  #    - uses: actions-rs/cargo@v1
  #      with:
  #        command: clippy
  #        args: --workspace --all-targets -- -D warnings

  test_win:
    name: Test Suite (Windows)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- os: ubuntu-latest
          #  TARGET: arm-unknown-linux-musleabihf

          #- os: ubuntu-latest
          #  TARGET: armv7-unknown-linux-musleabihf

          #- os: ubuntu-latest
          #  TARGET: x86_64-unknown-linux-musl

          #- os: macos-latest
          #  TARGET: aarch64-apple-darwin

          #- os: macos-latest
          #  TARGET: x86_64-apple-darwin

          - os: windows-2025
            ARCH: x86_64
            TARGET: x86_64-pc-windows-msvc
            EXTENSION: .exe

          - os: windows-2025
            ARCH: aarch64
            TARGET: aarch64-pc-windows-msvc
            EXTENSION: .exe

    steps:
      - name: Testing ${{ matrix.TARGET }}
        run: echo "${{ matrix.TARGET }}"

      - uses: milliewalky/setup-7-zip@v2

      - uses: actions/checkout@v4

      - run: mkdir vendor\mpv-dev-${{ matrix.ARCH }}
      - run: 7z x -y -ovendor\mpv-dev-${{ matrix.ARCH }} vendor\mpv-dev-${{ matrix.ARCH }}-20250923-git-ee0f701.7z
      - run: mv vendor\mpv-dev-${{ matrix.ARCH }}\libmpv.dll.a vendor\mpv-dev-${{ matrix.ARCH }}\mpv.lib
      - run: dir vendor\mpv-dev-${{ matrix.ARCH }}\

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
          override: true
      - run: rustc -vV

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  #build:
  #  name: Release Build
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      include:
  #        - os: ubuntu-latest
  #          TARGET: arm-unknown-linux-musleabihf

  #        - os: ubuntu-latest
  #          TARGET: armv7-unknown-linux-musleabihf

  #        - os: ubuntu-latest
  #          TARGET: x86_64-unknown-linux-musl

  #        - os: macos-latest
  #          TARGET: aarch64-apple-darwin

  #        - os: macos-latest
  #          TARGET: x86_64-apple-darwin

  #        - os: windows-latest
  #          TARGET: x86_64-pc-windows-msvc
  #          EXTENSION: .exe

  #  steps:
  #    - name: Building ${{ matrix.TARGET }}
  #      run: echo "${{ matrix.TARGET }}"

  #    - uses: actions/checkout@master
  #    - uses: actions-rs/toolchain@v1.0.1
  #      with:
  #        toolchain: stable
  #        target: ${{ matrix.TARGET }}
  #        override: true

  #    - uses: actions-rs/cargo@v1
  #      with:
  #        use-cross: true
  #        command: build
  #        args: --verbose --release --target=${{ matrix.TARGET }}
